name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Flutter
        id: flutter
        uses: actions/cache@v3
        with:
          path: ~/flutter
          key: ${{ runner.os }}-flutter

      - name: Install Flutter
        if: steps.flutter.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch stable https://github.com/flutter/flutter.git ~/flutter

      - name: Setup Flutter
        run: |
          echo "~/flutter/bin" >> $GITHUB_PATH

      - name: Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: meshtastic-controller
          path: build/app/outputs/flutter-apk/app-debug.apk
